name: github pages

on:
  push:
    branches:
      - master # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - run: zip -r dist.zip dist
    #   - run: apt-get install sshpass
    #   - run: sshpass -p ${{ secrets.PASSWORD }} scp -P 22 ./dist.zip root@${{ secrets.HOST }}:/usr/share/nginx/html/root/root
    #   - run: scp -r ./dist.zip  root@${{ secrets.HOST }}:/usr/share/nginx/html/root/root
      - name: Copy single file to remote
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.HOST }}
          port: 22
          user: root
          pass: ${{ secrets.PASSWORD }}
          run: sshpass -p ${{ secrets.PASSWORD }} scp -P 22 ./dist.zip root@${{ secrets.HOST }}:/usr/share/nginx/html/root/root
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          script: rm -rf /usr/share/nginx/html/root/root && cd /usr/share/nginx/html/root/root && unzip dist.zip