name: github pages

on:
  push:
    branches:
      - master # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - uses: actions/checkout@master
      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
      - name: cp files to aliyun
        run: ossutil cp -rf ./dist oss://wenhaoming-blog/
    #   - run: tar -zcvf ./dist.tar.gz ./dist
    #   - name: clear root directory
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.HOST }}
    #       username: root
    #       password: ${{ secrets.PASSWORD }}
    #       script: rm -rf /usr/share/nginx/html/root/root && mkdir /usr/share/nginx/html/root/root
    #   - name: Copy single file to remote
    #     uses: appleboy/scp-action@master
    #     with:
    #         host: ${{ secrets.HOST }}
    #         username: root
    #         password: ${{ secrets.PASSWORD }}
    #         port: 22
    #         source: dist
    #         target: /usr/share/nginx/html/root/root
